#!/usr/bin/env python3

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'src'))

print("=" * 60)
print("FBChat-V2 - Facebook Messaging Bot Library")
print("=" * 60)
print()
print("Welcome! This is a library for creating Facebook chatbots.")
print()
print("IMPORTANT SETUP INSTRUCTIONS:")
print("-" * 60)
print("1. This library requires a valid Facebook cookie to work")
print("2. To get your cookie:")
print("   - Login to Facebook in your browser")
print("   - Press F12 to open DevTools")
print("   - Go to Application/Storage > Cookies")
print("   - Copy the cookie value")
print()
print("3. Edit src/main.py and replace '<cookie-facebook>' with")
print("   your actual cookie value")
print()
print("4. Customize bot commands in the receiveCommandAndSend method")
print()
print("5. Run: python src/main.py")
print()
print("=" * 60)
print("DOCUMENTATION:")
print("=" * 60)
print("- README: See README.rst for Vietnamese documentation")
print("- README_EN: See README_EN.rst for English documentation")
print("- DOCS: See DOCS.md for detailed API documentation")
print()
print("KEY FEATURES:")
print("  • Receive messages from Facebook groups")
print("  • Send text messages and attachments")
print("  • Custom command handling with prefix support")
print("  • MQTT-based real-time message listening")
print()
print("⚠️  WARNING:")
print("  This is NOT an official Facebook API.")
print("  Use at your own risk. May violate Facebook ToS.")
print()
print("=" * 60)
print()
print("Dependencies installed successfully:")
print("  ✓ requests")
print("  ✓ paho-mqtt")
print("  ✓ attrs")
print()
print("Ready to use! Check the documentation for next steps.")
print("=" * 60)
